setup:
  type: list
  default: 'staff, 3'
  description: |
    Each line should be in the format of "<code>category-slug</code> (show), <code>category-slug</code> (source), qty".<br/><br/>
    <ul>
    <li>The category slug is the category name from its url, for example /c/<b>site-feedback</b></li>
    <li>If you'd like to set a sidebar for /latest, /top, /new, /unread, use <code>all</code> as the category slug</li>
    </ul>
    <p>For performance reasons it's recommended that you close sidebar topics so there aren't any replies</p>